#!/bin/sh

# uncomment the stuff you want to use

#xwallpaper --zoom $HOME/wlp/something.png &
xrdb $HOME/.Xresources
#sxhkd -c $HOME/.config/sxhkd/sxhkdrc &
picom --backend xrender --vsync &
#. $HOME/sh/bar.sh &
#exec berry
#exec sdorfehs
