#!/bin/sh

# Set decoration geometry
berryc border_width       3
berryc inner_border_width 3
berryc title_height       0
berryc edge_gap           20 0 0 0 # for lemonbar

# Set decoration colors
berryc focus_color         f2f3f5
berryc unfocus_color       f2f3f5
berryc inner_focus_color   56667d
berryc inner_unfocus_color abb3be
berryc text_focus_color    f2f3f5
berryc text_unfocus_color  f2f3f5

# Misc.
berryc smart_place "false"
berryc draw_text   "false"
berryc edge_lock   "true"
berryc set_font    "MxPlus IBM VGA 8x16"
berryc resize_mask "mod4"
berryc move_mask   "mod1"

. $HOME/sh/clock.sh & # balls. useless clock.
